# Generated by Django 6.0.5 on 2026-05-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='model_used',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
